Launch Arguments
Alexander-Ignition/UI-Testing pull request #1
Opened 2020-04-01 07:11 UTC by Alexander-Ignition

2020-04-01 07:26 UTC, subdan commented on LaunchArguments/README.md
> +- Для передачи значения оно должно стоять сразу после ключа `["-key", "value"]`
Может быть здесь показать как передать несколько параметров?

2020-04-01 07:26 UTC, subdan commented on LaunchArguments/README.md
> +Мы можем в ручную прописать для нужной нам схемы аргументы, которые Xcode передаст при запуске приложения. Это может помочь в отладке приложения.
вручную

2020-04-01 07:27 UTC, subdan commented on LaunchArguments/README.md
> +`launchArguments` делают тоже самое, что и Xcode Scheme.
тоже самое, что и **Arguments Passed On Launch** указанные в Xcode Scheme

2020-04-01 07:29 UTC, subdan commented on LaunchArguments/README.md
> +Как видно из картинки мы можем динамически включать и отключать аргументы запуска.
Но ведь эти аргументы не используются при UI-тестировании. Нужно ли это здесь писать?

2020-04-01 07:29 UTC, subdan commented on LaunchArguments/README.md
> +Что ж как передать аргументы мы разобрались. Для их использования внутри прилоения у нас есть два пути `ProcessInfo` и `UserDefaults`
приложения

2020-04-01 07:29 UTC, subdan commented on LaunchArguments/README.md
> +В `ProcessInfo` доступны абсолютно все пргументы.
:( пргументы

2020-04-02 13:06 UTC, vani2 requested changes

2020-04-02 13:06 UTC, vani2 commented on LaunchArguments/README.md
> +### XCode
Xcode

2020-04-02 13:06 UTC, vani2 commented on LaunchArguments/README.md
> +Что ж как передать аргументы мы разобрались. Для их использования внутри приложения у нас есть два пути `ProcessInfo` и `UserDefaults`
Что ж, как

2020-04-02 13:06 UTC, vani2 commented on LaunchArguments/README.md
> +Что ж как передать аргументы мы разобрались. Для их использования внутри приложения у нас есть два пути `ProcessInfo` и `UserDefaults`
два пути:

2020-04-02 13:06 UTC, vani2 commented on LaunchArguments/README.md
> +Но хорошо что есть более удобная альтернатива  `ProcessInfo`
Тут надо исправить либо 

> более удобная альтернатива  `ProcessInfo` — `UserDefaults`.

либо 
> более удобная альтернатива   — `UserDefaults`.

2020-04-02 13:06 UTC, vani2 commented on LaunchArguments/README.md
> +- Оборачивайте куски кода использующего аргументы из UI тестов в блоки #if DEBUG (или другой ваш аналог), чтобы код не попал в релиз.
`#if DEBUG` можно в кавычки

2020-04-02 13:06 UTC, vani2 commented on LaunchArguments/README.md
> +Одной из первых необходимостей при начале UI тестирования приложения встает вопросы передачи параметров для настройки приложения.
Звучит сложновато. 
> Один из первых вопросов при UI тестировании — как передавать параметры извне для настройки приложения.

2020-04-08 06:54 UTC, merged